#ifndef DualManipulatorCommonInterface_IDL
#define DualManipulatorCommonInterface_IDL

module DualManipulatorCommonInterface{

typedef double HgMatrix [3][4];
typedef sequence<double> DoubleSeq;
typedef sequence<double> JointPos;
typedef sequence<JointPos> JointPosSeq;
typedef unsigned long ULONG;
  
struct RETURN_ID {
  long id;
  string comment;
};

struct CarPosWithElbow {
  HgMatrix carPos;
  double elbow;
  ULONG structFlag;
};
  
interface CommonCommands {

  RETURN_ID servoOFF();
  RETURN_ID servoON();
  RETURN_ID servoOFFArm();
  RETURN_ID servoOFFHand();
  RETURN_ID servoONArm();
  RETURN_ID servoONHand();

};

interface MotionCommands {
  
  RETURN_ID closeGripper();
  RETURN_ID moveGripper(in DoubleSeq r_angle, in DoubleSeq l_angle);
  RETURN_ID moveLinearCartesianAbs(in CarPosWithElbow rArm, in CarPosWithElbow lArm);
  RETURN_ID moveLinearCartesianRel(in CarPosWithElbow rArm, in CarPosWithElbow lArm);
  RETURN_ID movePTPJointAbs(in JointPos jointPoints);
  RETURN_ID movePTPJointRel(in JointPos jointPoints);
  RETURN_ID movePTPJointAbsSeq(in JointPosSeq jointPointsSeq);
  RETURN_ID openGripper();
  RETURN_ID setSpeedCartesian(in ULONG spdRatio);
  RETURN_ID setSpeedJoint(in ULONG spdRatio);

};
};

#endif /* DualManipulatorCommonInterface_IDL */ 
